import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TrpcProvider from "@/lib/trpc/Provider";
import NextAuthProvider from "@/lib/auth/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TrpcProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </TrpcProvider>
      </body>
    </html>
  );
}
